# Generated by Django 5.2.8 on 2025-11-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('employment_agriculture', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizersByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('fertilizer_type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignDirectInvestmentAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investing_country', models.CharField(max_length=255)),
                ('receiving_country', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('investment_amount', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('land_area_agricultural', models.FloatField()),
                ('land_area_total', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCropsLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('production_quantity', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
    ]
