# Generated by Django 5.2.8 on 2025-11-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentagriculture',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fertilizersbyproduct',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='foreigndirectinvestmentagriculture',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='landuse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producerprices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productioncropslivestock',
            options={'managed': False},
        ),
    ]
