# Generated by Django 5.2.4 on 2025-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0002_alter_employmentagriculture_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employmentagriculture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="fertilizersbyproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="foreigndirectinvestmentagriculture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="landuse",
            options={},
        ),
        migrations.AlterModelOptions(
            name="producerprices",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productioncropslivestock",
            options={},
        ),
    ]
