# Generated by Django 5.2.4 on 2025-11-18 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0003_alter_employmentagriculture_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employmentagriculture",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="fertilizersbyproduct",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="foreigndirectinvestmentagriculture",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="landuse",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="producerprices",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="productioncropslivestock",
            options={"managed": False},
        ),
    ]
