# Generated by Django 5.2.4 on 2025-11-18 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_alter_employmentagriculture_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employmentagriculture",
            table="production_employmentagriculture",
        ),
        migrations.AlterModelTable(
            name="fertilizersbyproduct",
            table="production_fertilizersbyproduct",
        ),
        migrations.AlterModelTable(
            name="foreigndirectinvestmentagriculture",
            table="production_foreigndirectinvestmentagriculture",
        ),
        migrations.AlterModelTable(
            name="landuse",
            table="production_landuse",
        ),
        migrations.AlterModelTable(
            name="producerprices",
            table="production_producerprices",
        ),
        migrations.AlterModelTable(
            name="productioncropslivestock",
            table="production_productioncropslivestock",
        ),
    ]
